repos:
  - repo: local
    hooks:
      - id: task-pre-commit
        name: task pre-commit
        entry: task pre-commit
        language: system
        pass_filenames: false
        always_run: true
