# This workflow will install Python dependencies, run tests and lint on Python 3.10
# with the newest versions of the dependencies on MacOS and Windows.

name: MacOS and Windows Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --requirement requirements.txt
    - name: Test with pytest
      run: |
        pytest
