# This workflow will install Python dependencies, run tests and lint on Python 3.8
# with the minimum versions of the dependencies on Ubuntu.

name: Ubuntu Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest flake8
        python -m pip install pyarrow==8.0.0
        python -m pip install pandas==1.1.0
        python -m pip install polars[timezone]==0.14.11
    - name: Test with pytest
      run: |
        pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --select=E9,F63,F7,F82 --show-source --statistics --count
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --exit-zero --max-complexity=10 --ignore=F405,F403 --max-line-length=100 --statistics --count