# This workflow will install Python dependencies, run tests and lint on Python 3.11
# with the minimum versions of the dependencies on Ubuntu.

name: Ubuntu Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v8
      with:
        python-version: "3.11"
        enable-cache: true
    - name: Install dependencies
      run: |
        uv pip install pytest ruff pyarrow==14.0.0 pandas==2.2.0 'polars[timezone]==1.21.0'
        uv pip install -e .
    - name: Test with pytest
      run: uv run pytest
    - name: Lint with ruff
      run: |
        uv run ruff check featherstore tests
        uv run ruff format --check featherstore tests
