# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Ubuntu Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
        pandas-version: ["1.2.0", "1.5.0"]
        pyarrow-version: ["7.0.0", "9.0.0"]
        polars-version: ["0.14.11", "0.14.22"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pyarrow==${{ matrix.pyarrow-version }}
        python -m pip install pandas==${{ matrix.pandas-version }}
        python -m pip install polars[timezone]==${{ matrix.polars-version }}
    - name: Test with pytest
      run: |
        pytest
